version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Paris"
    open-pull-requests-limit: 100
    commit-message:
      prefix: chore
      include: scope
